CREATE TABLE IF NOT EXISTS `collaboration_record` (
  `id` int NOT NULL AUTO_INCREMENT,
  `project_id` int NOT NULL,
  `tool_id` int DEFAULT NULL,
  `reservation_id` int DEFAULT NULL,
  `usage_event_id` int DEFAULT NULL,
  `task_id` int DEFAULT NULL,
  `maintenance_record_id` int DEFAULT NULL,
  `author_id` int NOT NULL,
  `record_type` varchar(40) NOT NULL,
  `title` varchar(200) NOT NULL,
  `content` longtext NOT NULL,
  `content_format` varchar(30) NOT NULL DEFAULT 'markdown',
  `visibility` varchar(30) NOT NULL DEFAULT 'project',
  `status` varchar(30) NOT NULL DEFAULT 'draft',
  `pinned` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_collab_project_type_created` (`project_id`, `record_type`, `created_at`),
  KEY `ix_collab_tool_type_created` (`tool_id`, `record_type`, `created_at`),
  KEY `ix_collab_reservation_id` (`reservation_id`),
  KEY `ix_collab_author_created` (`author_id`, `created_at`),
  KEY `ix_collab_status` (`status`),
  KEY `ix_collab_deleted_at` (`deleted_at`),
  CONSTRAINT `fk_collab_project` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_collab_tool` FOREIGN KEY (`tool_id`) REFERENCES `tool` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_collab_reservation` FOREIGN KEY (`reservation_id`) REFERENCES `reservation` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_collab_usage_event` FOREIGN KEY (`usage_event_id`) REFERENCES `usage_event` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_collab_task` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_collab_maintenance` FOREIGN KEY (`maintenance_record_id`) REFERENCES `maintenance_record` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_collab_author` FOREIGN KEY (`author_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
